### ISSUE TITLE
Develop the backend of the project

### ISSUE THREAD

**Issue by Kalogirou-Va** [SpGianniler/schedule-manager#3]
Develop the basic functions of the project based on the application of the previous semester

**Comment by Apostolos-Valiakos** [comment]
Δημιουργία κλάσης ανάγνωσης από τη βάση με τους αντίστοιχους getters.
Δημιουργία κλάσης εργαζομένων και τους αντιστοιχους constructors (με ορίσματα).
Δημιουργία συνδεδεμένης λίστας αντικειμένων "Εργαζόμενοι" χρησιμοποοιώντας τους getters και τον construstor.
